### ISSUE TITLE
add_spotify_to_queue fails

### ISSUE THREAD

**Issue by wstrinz** [gotwalt/sonos#34]
I know its a pretty recent addition, but when I try and use the `add_spotify_to_queue` method I get 

```
2.0.0p353 :006 > speaker.add_spotify_to_queue(id: '2CwulIyrmEYwbUWzcEVIhR')
Savon::SOAPFault: (s:Client) UPnPError
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/response.rb:14:in `initialize'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/operation.rb:64:in `new'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/operation.rb:64:in `create_response'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/operation.rb:55:in `call'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/client.rb:36:in `call'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/sonos-0.3.5/lib/sonos/endpoint/a_v_transport.rb:197:in `send_transport_message'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/sonos-0.3.5/lib/sonos/endpoint/a_v_transport.rb:108:in `add_to_queue'
    from /Users/willstrinz/.rvm/gems/ruby-2.0.0-p353/gems/sonos-0.3.5/lib/sonos/endpoint/a_v_transport.rb:156:in `add_spotify_to_queue'
    from (irb):6
    from /Users/willstrinz/.rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'
```

I can successfully add tracks using the old method (`speaker.add_to_queue 'x-sonos-spotify:spotify%3atrack%3a60KbvwQPIv8soov3wzbySK?sid=9&amp;flags=0'`), so I think my spotify connection is ok. I'll take a look and see if I can track down the error further.

**Comment by jasperla** [comment]
Could you turn the level level to 11 with:

```ruby
Sonos.logging_enabled = 'debug'
```

**Comment by nmyster** [comment]
I have been encountering this issue too.

I notice if I do the following:
speakers.add_to_queue 'x-sonos-spotify:spotify%3atrack%3a#1AhDOtG9vPSOmsWgNW0BEY?sid=9&flags=32'

I get the same UPNP error as mentioned.

However, if I try 
speakers.add_to_queue 'x-sonos-spotify:spotify%3atrack%3a#1AhDOtG9vPSOmsWgNW0BEY'
with the flags/sid parameters missing it doesn't return the same error and an item is added to the queue... But not something that can be played.
http://puu.sh/ebD93/ae92006e06.png

Additionally, if use the previous example but only use 1 flag (no & used) the same result happens.

Could it be something to do with how the & is being parsed.

**Comment by nmyster** [comment]
I find replacing & with %26 it works better but not perfect
